name: Update Flake inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-nixpkgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        id: update_flakes
        with:
          pr-title: "Update flake.lock"
          pr-labels: dependencies
